name: Build/Test

on:
  push:
    branches: [ main ]
    paths-ignore:
    - '**/README.md'
    - '**/nuget_readme.md'
  pull_request:
    branches: [ main ]
    paths-ignore:
    - '**/README.md'
    - '**/nuget_readme.md'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: |
          6.x
          7.x
    - name: Build
      run: dotnet build -c Release Sources/Handler/Salix.AspNetCore.JsonExceptionHandler.csproj

    - name: Test
      run: dotnet test
